import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone Next.js</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-2xl'>Hello World</h1>
    </div>
  );
}
